# Generated by Django 5.1.2 on 2024-10-25 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='введите название', max_length=100, verbose_name='Название')),
                ('description', models.TextField(help_text='введите описание', verbose_name='Описание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='materials/image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='введите название', max_length=100, verbose_name='Название')),
                ('description', models.TextField(help_text='введите описание', verbose_name='Описание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='materials/image', verbose_name='Изображение')),
                ('link', models.URLField(blank=True, help_text='введите ссылку на видео', null=True, verbose_name='Видео')),
                ('course', models.ForeignKey(help_text='выберите курс', on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
    ]
